#!/usr/bin/perl -CSDAL

use warnings;
use strict;
use Getopt::Long;
use IServ::DNSOverTLS;

sub help()
{
  print <<EOT;
Usage: $0 [options]
--enabled, -e   Check if it at least for one server in resolvconf is whitelisted
                for DNS over tls. Will exit with code 1 if not.
--help, -h      Show this help
--unbound, -u   Print list of DNS over TLS servers in unbound forwarders style.
EOT

}

GetOptions(\my %opt,
  "enabled|e",
  "help|h",
  "unbound|u"
) or help and exit 1;

if ($opt{enabled})
{
  my %current = GetCurrentNameservers;
  exit if grep { $current{$_} == 1; } keys %current;
  exit 1;
}
elsif ($opt{help})
{
  help;
  exit;
}
elsif ($opt{unbound})
{
  my %current = GetCurrentNameservers;
  print "$_\@853\n" for grep { $current{$_} == 1; } keys %current;
}

my $state = GetNameserverState;

for (@ARGV)
{
  print "$_\n" if exists $state->{$_} and $state->{$_} == 1;
}
