#!/usr/bin/perl -CSDAL

use warnings;
use strict;
use Getopt::Long;
use IServ::DNSOverTLS;

sub help()
{
  print <<EOT;
Usage: $0 [options]
--enabled, -e   Check if it at least for one server in resolvconf is whitelisted
                for DNS over tls. Will exit with code 1 if not.
--help, -h      Show this help
--unbound, -u   Print list of DNS over TLS servers in unbound forwarders style.
EOT

}

GetOptions(\my %opt,
  "enabled|e",
  "help|h",
  "unbound|u"
) or help and exit 1;

if ($opt{enabled})
{
  my %current = GetCurrentNameservers;
  exit 0 if grep { $current{$_}{activate}; } sort keys %current;
  exit 1;
}
elsif ($opt{help})
{
  help;
  exit;
}
elsif ($opt{unbound})
{
  my %current = GetCurrentNameservers;
  do {
    print "$_\@853";
    print "#$current{$_}{hostname}" if $current{$_}{hostname};
    print "\n";
  } for grep { $current{$_}{activate}; } sort @ARGV;
  exit;
}

my $state = GetNameserverState;

for (sort @ARGV)
{
  print "$_\n" if $state->{$_}->{activate};
}
