#!/bin/sh
set -e

case "$1" in
  remove|purge|abort-install|disappear)
    if ! dpkg-divert --list | grep -F "/etc/resolvconf/update.d/bind.distrib"
    then
      rm -f /etc/resolvconf/update.d/bind
      dpkg-divert --remove --rename /etc/resolvconf/update.d/bind
    fi
  ;;
esac

case "$1" in
  remove|purge)
    rm -f /etc/resolvconf/update.d/unbound-iserv
    systemctl daemon-reload
  ;;
esac

#DEBHELPER#
