#!/bin/sh
set -e 

if [ "$1" = "remove" ] || [ "$1" = "purge" ]
then
  rm -f /etc/stunnel/iserv-dns-over-tls.conf
  for f in /etc/stunnel/iserv-dns-over-tls.conf*
  do
    rm -f "$f"
  done
  deb-systemd-invoke restart stunnel4 || true

  # stunnel4 unit lefts its children behind sometimes...
  grep -l '^/usr/bin/stunnel4'"$(printf "\0")"'/etc/stunnel/iserv-dns-over-tls.conf$' /proc/*/cmdline ||: |
      awk -F/ '{ print $3 }' |
      xargs -r kill
fi

#DEBHELPER#
